/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FragmentsRouteImport } from './routes/fragments'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PartialsRouteImport } from './routes/partials'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProjectsRouteImport } from './routes/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FragmentsRoute = FragmentsRouteImport.update({
  id: '/fragments',
  path: '/fragments',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PartialsRoute = PartialsRouteImport.update({
  id: '/partials',
  path: '/partials',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fragments': typeof FragmentsRoute
  '/history': typeof HistoryRoute
  '/partials': typeof PartialsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fragments': typeof FragmentsRoute
  '/history': typeof HistoryRoute
  '/partials': typeof PartialsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fragments': typeof FragmentsRoute
  '/history': typeof HistoryRoute
  '/partials': typeof PartialsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/fragments' | '/history' | '/partials' | '/playground' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/fragments' | '/history' | '/partials' | '/playground' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/fragments'
    | '/history'
    | '/partials'
    | '/playground'
    | '/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FragmentsRoute: typeof FragmentsRoute
  HistoryRoute: typeof HistoryRoute
  PartialsRoute: typeof PartialsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragments': {
      id: '/fragments'
      path: '/fragments'
      fullPath: '/fragments'
      preLoaderRoute: typeof FragmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partials': {
      id: '/partials'
      path: '/partials'
      fullPath: '/partials'
      preLoaderRoute: typeof PartialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FragmentsRoute: FragmentsRoute,
  HistoryRoute: HistoryRoute,
  PartialsRoute: PartialsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
